// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: internal/proto/weather/weather.proto

package weather

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WeatherUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Latitude      float64                `protobuf:"fixed64,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Temperature   float32                `protobuf:"fixed32,3,opt,name=temperature,proto3" json:"temperature,omitempty"`
	WindSpeed     float32                `protobuf:"fixed32,4,opt,name=wind_speed,json=windSpeed,proto3" json:"wind_speed,omitempty"`
	Conditions    string                 `protobuf:"bytes,5,opt,name=conditions,proto3" json:"conditions,omitempty"`
	Timestamp     int64                  `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WeatherUpdate) Reset() {
	*x = WeatherUpdate{}
	mi := &file_internal_proto_weather_weather_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WeatherUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WeatherUpdate) ProtoMessage() {}

func (x *WeatherUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_weather_weather_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WeatherUpdate.ProtoReflect.Descriptor instead.
func (*WeatherUpdate) Descriptor() ([]byte, []int) {
	return file_internal_proto_weather_weather_proto_rawDescGZIP(), []int{0}
}

func (x *WeatherUpdate) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *WeatherUpdate) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *WeatherUpdate) GetTemperature() float32 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *WeatherUpdate) GetWindSpeed() float32 {
	if x != nil {
		return x.WindSpeed
	}
	return 0
}

func (x *WeatherUpdate) GetConditions() string {
	if x != nil {
		return x.Conditions
	}
	return ""
}

func (x *WeatherUpdate) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_internal_proto_weather_weather_proto protoreflect.FileDescriptor

const file_internal_proto_weather_weather_proto_rawDesc = "" +
	"\n" +
	"$internal/proto/weather/weather.proto\x12\aweather\"\xc8\x01\n" +
	"\rWeatherUpdate\x12\x1a\n" +
	"\blatitude\x18\x01 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x02 \x01(\x01R\tlongitude\x12 \n" +
	"\vtemperature\x18\x03 \x01(\x02R\vtemperature\x12\x1d\n" +
	"\n" +
	"wind_speed\x18\x04 \x01(\x02R\twindSpeed\x12\x1e\n" +
	"\n" +
	"conditions\x18\x05 \x01(\tR\n" +
	"conditions\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x03R\ttimestampB%Z#routePlanner/internal/proto/weatherb\x06proto3"

var (
	file_internal_proto_weather_weather_proto_rawDescOnce sync.Once
	file_internal_proto_weather_weather_proto_rawDescData []byte
)

func file_internal_proto_weather_weather_proto_rawDescGZIP() []byte {
	file_internal_proto_weather_weather_proto_rawDescOnce.Do(func() {
		file_internal_proto_weather_weather_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_weather_weather_proto_rawDesc), len(file_internal_proto_weather_weather_proto_rawDesc)))
	})
	return file_internal_proto_weather_weather_proto_rawDescData
}

var file_internal_proto_weather_weather_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_internal_proto_weather_weather_proto_goTypes = []any{
	(*WeatherUpdate)(nil), // 0: weather.WeatherUpdate
}
var file_internal_proto_weather_weather_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_proto_weather_weather_proto_init() }
func file_internal_proto_weather_weather_proto_init() {
	if File_internal_proto_weather_weather_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_weather_weather_proto_rawDesc), len(file_internal_proto_weather_weather_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_proto_weather_weather_proto_goTypes,
		DependencyIndexes: file_internal_proto_weather_weather_proto_depIdxs,
		MessageInfos:      file_internal_proto_weather_weather_proto_msgTypes,
	}.Build()
	File_internal_proto_weather_weather_proto = out.File
	file_internal_proto_weather_weather_proto_goTypes = nil
	file_internal_proto_weather_weather_proto_depIdxs = nil
}
