apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090  # Inside Docker, use the service name
    isDefault: true
    uid: my-prometheus-datasource